// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShopDMZ.Data;

namespace eShopDMZ.Migrations
{
    [DbContext(typeof(eShopContext))]
    [Migration("20210115153945_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("eShopDMZ.Models.TBCategoria", b =>
                {
                    b.Property<int>("IDCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCategoria");

                    b.ToTable("TBCategoria");
                });

            modelBuilder.Entity("eShopDMZ.Models.TBFornecedor", b =>
                {
                    b.Property<int>("IDFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDFornecedor");

                    b.ToTable("TBFornecedor");
                });

            modelBuilder.Entity("eShopDMZ.Models.TBProduto", b =>
                {
                    b.Property<int>("IDProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDFornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TBCategoriaIDCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("TBFornecedorIDFornecedor")
                        .HasColumnType("int");

                    b.Property<string>("Tamanho")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDProduto");

                    b.HasIndex("TBCategoriaIDCategoria");

                    b.HasIndex("TBFornecedorIDFornecedor");

                    b.ToTable("TBProduto");
                });

            modelBuilder.Entity("eShopDMZ.Models.TBProduto", b =>
                {
                    b.HasOne("eShopDMZ.Models.TBCategoria", null)
                        .WithMany("TBProduto")
                        .HasForeignKey("TBCategoriaIDCategoria");

                    b.HasOne("eShopDMZ.Models.TBFornecedor", null)
                        .WithMany("TBProduto")
                        .HasForeignKey("TBFornecedorIDFornecedor");
                });

            modelBuilder.Entity("eShopDMZ.Models.TBCategoria", b =>
                {
                    b.Navigation("TBProduto");
                });

            modelBuilder.Entity("eShopDMZ.Models.TBFornecedor", b =>
                {
                    b.Navigation("TBProduto");
                });
#pragma warning restore 612, 618
        }
    }
}
